/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopPanel.java
 *
 * Created on 22.Eki.2011, 17:23:52
 */

package xcompany.userInterface;

/**
 *
 * @author Mert
 */
public class TopPanel extends javax.swing.JPanel {

    /** Creates new form TopPanel */
    public TopPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        labelNameSurname = new javax.swing.JLabel();
        labelUserType = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(198, 212, 225));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(68, 116, 157), 1, true));
        setForeground(new java.awt.Color(235, 231, 224));
        setMinimumSize(new java.awt.Dimension(700, 0));
        setPreferredSize(new java.awt.Dimension(700, 78));

        labelUsername.setText("jLabel1");

        labelNameSurname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNameSurname.setText("jLabel1");

        labelUserType.setText("jLabel1");

        buttonLogout.setText("Logout");

        buttonEdit.setText("Edit Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUserType)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsername)
                            .addComponent(labelNameSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 579, Short.MAX_VALUE)
                        .addComponent(buttonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogout)
                    .addComponent(buttonEdit))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNameSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserType)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JLabel labelNameSurname;
    private javax.swing.JLabel labelUserType;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables

}
