/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Forms.java
 *
 * Created on Oct 22, 2011, 3:43:15 PM
 */

package xcompany.userInterface;

/**
 *
 * @author Emertat
 */
public class Forms extends javax.swing.JPanel {

    /** Creates new form Forms */
    public Forms() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1SimpleForm = new javax.swing.JLabel();
        jLabel1Name = new javax.swing.JLabel();
        jTextField1Name = new javax.swing.JTextField();
        jLabel1Surname = new javax.swing.JLabel();
        jTextField2Surname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2Email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2Date = new javax.swing.JTextField();
        jLabel3AccidentAddress = new javax.swing.JLabel();
        jTextField2AccidentAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2WitnessName = new javax.swing.JTextField();
        jLabel4WitnessSurname = new javax.swing.JLabel();
        jTextField2WitnessSurname = new javax.swing.JTextField();
        jLabel4LicensePlate = new javax.swing.JLabel();
        jTextField2Licenseplate = new javax.swing.JTextField();
        jLabel4VehicleModel = new javax.swing.JLabel();
        jTextField2VehicleModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2DamageDescription = new javax.swing.JTextField();
        jButton1SimpleFormSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6NameC = new javax.swing.JLabel();
        jTextField2NameC = new javax.swing.JTextField();
        jLabel6SurnameC = new javax.swing.JLabel();
        jTextField2SurnameC = new javax.swing.JTextField();
        jLabel6EmailC = new javax.swing.JLabel();
        jTextField2EmailC = new javax.swing.JTextField();
        jLabel6DateC = new javax.swing.JLabel();
        jTextField2DateC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2AccidentAddressC = new javax.swing.JTextField();
        jLabel7WitnessNameC = new javax.swing.JLabel();
        jTextField2WitnessNameC = new javax.swing.JTextField();
        jLabel7WitnessSurnameC = new javax.swing.JLabel();
        jTextField2WitnessSurnameC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2LicensePlateC = new javax.swing.JTextField();
        jLabel8VehicleModel = new javax.swing.JLabel();
        jTextField2VehicleModelC = new javax.swing.JTextField();
        jLabel8DamageDecription = new javax.swing.JLabel();
        jTextField2DamageDescriptionC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2Name2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2Surname2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2LicensePlate2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2VehicleModel2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2DamageDescription2 = new javax.swing.JTextField();
        jButton1SubmitC = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1SimpleForm.setText("Simple Form");

        jLabel1Name.setText("Name");

        jTextField1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NameActionPerformed(evt);
            }
        });

        jLabel1Surname.setText("Surname");

        jLabel1.setText("Email");

        jLabel2.setText("Date");

        jLabel3AccidentAddress.setText("Accident Address");

        jLabel3.setText("Witness Name");

        jLabel4WitnessSurname.setText("Witness Surname");

        jLabel4LicensePlate.setText("License Plate");

        jLabel4VehicleModel.setText("vehicle Model");

        jLabel4.setText("Damage Description");

        jTextField2DamageDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2DamageDescriptionActionPerformed(evt);
            }
        });

        jButton1SimpleFormSubmit.setText("Submit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1SimpleForm, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1Name, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1Surname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3AccidentAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(84, 84, 84))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1SimpleFormSubmit)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4WitnessSurname)
                                    .addGap(84, 84, 84)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4LicensePlate)
                                .addGap(102, 102, 102)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4VehicleModel)
                            .addGap(103, 103, 103)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2DamageDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2VehicleModel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2Licenseplate, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2WitnessSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2WitnessName, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2AccidentAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2Email, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField2Surname, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jTextField1Name, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1SimpleForm)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Name)
                    .addComponent(jTextField1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Surname)
                    .addComponent(jTextField2Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2Email, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2Date, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3AccidentAddress)
                    .addComponent(jTextField2AccidentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2WitnessName, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4WitnessSurname)
                    .addComponent(jTextField2WitnessSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4LicensePlate)
                    .addComponent(jTextField2Licenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4VehicleModel)
                    .addComponent(jTextField2VehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2DamageDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1SimpleFormSubmit)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel5.setText("Complex Form");

        jLabel6NameC.setText("Name");

        jLabel6SurnameC.setText("Surname");

        jLabel6EmailC.setText("Email");

        jTextField2EmailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EmailCActionPerformed(evt);
            }
        });

        jLabel6DateC.setText("Date");

        jLabel6.setText("Accident Address");

        jTextField2AccidentAddressC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2AccidentAddressCActionPerformed(evt);
            }
        });

        jLabel7WitnessNameC.setText("Witness Name");

        jLabel7WitnessSurnameC.setText("Witness Surname");

        jLabel7.setText("License Plate");

        jLabel8VehicleModel.setText("Vehicle Model");

        jLabel8DamageDecription.setText("Damage Description");

        jLabel8.setText("Name of other driver");

        jTextField2Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2Name2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Surname of other driver");

        jLabel10.setText("License Plate2");

        jLabel11.setText("Vehicle Model2");

        jLabel12.setText("Damage Description");

        jButton1SubmitC.setText("Submit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6SurnameC)
                                            .addComponent(jLabel6EmailC)
                                            .addComponent(jLabel6DateC)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7WitnessNameC)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8VehicleModel)
                                            .addComponent(jLabel8DamageDecription)
                                            .addComponent(jLabel8))
                                        .addGap(33, 33, 33))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6NameC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2Name2)
                                    .addComponent(jTextField2DamageDescriptionC)
                                    .addComponent(jTextField2VehicleModelC)
                                    .addComponent(jTextField2LicensePlateC)
                                    .addComponent(jTextField2WitnessSurnameC)
                                    .addComponent(jTextField2WitnessNameC)
                                    .addComponent(jTextField2AccidentAddressC)
                                    .addComponent(jTextField2EmailC)
                                    .addComponent(jTextField2SurnameC)
                                    .addComponent(jTextField2NameC, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField2DateC, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2DamageDescription2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField2VehicleModel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField2LicensePlate2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField2Surname2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                        .addGap(235, 235, 235))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7WitnessSurnameC)
                        .addContainerGap(386, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(374, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1SubmitC)
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6NameC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2NameC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2SurnameC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6SurnameC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2EmailC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6EmailC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2DateC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6DateC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2AccidentAddressC, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2WitnessNameC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7WitnessNameC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2WitnessSurnameC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7WitnessSurnameC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2LicensePlateC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2VehicleModelC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8VehicleModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2DamageDescriptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8DamageDecription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField2Surname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField2VehicleModel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField2DamageDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jButton1SubmitC))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jTextField2LicensePlate2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2DamageDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2DamageDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2DamageDescriptionActionPerformed

    private void jTextField2EmailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EmailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2EmailCActionPerformed

    private void jTextField2AccidentAddressCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2AccidentAddressCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2AccidentAddressCActionPerformed

    private void jTextField2Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2Name2ActionPerformed

    private void jTextField1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SimpleFormSubmit;
    private javax.swing.JButton jButton1SubmitC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1Name;
    private javax.swing.JLabel jLabel1SimpleForm;
    private javax.swing.JLabel jLabel1Surname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3AccidentAddress;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4LicensePlate;
    private javax.swing.JLabel jLabel4VehicleModel;
    private javax.swing.JLabel jLabel4WitnessSurname;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6DateC;
    private javax.swing.JLabel jLabel6EmailC;
    private javax.swing.JLabel jLabel6NameC;
    private javax.swing.JLabel jLabel6SurnameC;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7WitnessNameC;
    private javax.swing.JLabel jLabel7WitnessSurnameC;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8DamageDecription;
    private javax.swing.JLabel jLabel8VehicleModel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1Name;
    private javax.swing.JTextField jTextField2AccidentAddress;
    private javax.swing.JTextField jTextField2AccidentAddressC;
    private javax.swing.JTextField jTextField2DamageDescription;
    private javax.swing.JTextField jTextField2DamageDescription2;
    private javax.swing.JTextField jTextField2DamageDescriptionC;
    private javax.swing.JTextField jTextField2Date;
    private javax.swing.JTextField jTextField2DateC;
    private javax.swing.JTextField jTextField2Email;
    private javax.swing.JTextField jTextField2EmailC;
    private javax.swing.JTextField jTextField2LicensePlate2;
    private javax.swing.JTextField jTextField2LicensePlateC;
    private javax.swing.JTextField jTextField2Licenseplate;
    private javax.swing.JTextField jTextField2Name2;
    private javax.swing.JTextField jTextField2NameC;
    private javax.swing.JTextField jTextField2Surname;
    private javax.swing.JTextField jTextField2Surname2;
    private javax.swing.JTextField jTextField2SurnameC;
    private javax.swing.JTextField jTextField2VehicleModel;
    private javax.swing.JTextField jTextField2VehicleModel2;
    private javax.swing.JTextField jTextField2VehicleModelC;
    private javax.swing.JTextField jTextField2WitnessName;
    private javax.swing.JTextField jTextField2WitnessNameC;
    private javax.swing.JTextField jTextField2WitnessSurname;
    private javax.swing.JTextField jTextField2WitnessSurnameC;
    // End of variables declaration//GEN-END:variables

}
