/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GaragePanel.java
 *
 * Created on 24.Eki.2011, 01:04:13
 */

package xcompany.userInterface;

import java.io.IOException;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import xcompany.lists.*;
import xcompany.structures.*;
import xcompany.control.*;

/**
 *
 * @author Mert
 */
public class GaragePanel extends javax.swing.JPanel {

    /** Creates new form GaragePanel */
    ClaimList claimListCurrent;
    EmailList emailList = new EmailList();
    Garage garage;
    public GaragePanel(Garage garage) throws IOException, ClassNotFoundException {
        claimListCurrent = DatabaseControl.getAllClaims();
        this.garage = garage;
        TopPanel tp = new TopPanel(garage.getName(), garage.getEmail(), garage.getAddress());
        
        initComponents();
        panelTop.add(tp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        emailTable = new javax.swing.JTable(){
            @Override public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textTextArea = new javax.swing.JTextArea();
        panelTop = new javax.swing.JPanel();

        emailTable.setModel(getEmailsTableModel());
        emailTable.getSelectionModel().addListSelectionListener(new EmailsRowListener());
        jScrollPane4.setViewportView(emailTable);

        jLabel1.setText("From:");

        jLabel2.setText("To:");

        jLabel3.setText("Subject:");

        textTextArea.setColumns(20);
        textTextArea.setRows(5);
        jScrollPane5.setViewportView(textTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromLabel)
                            .addComponent(toLabel)
                            .addComponent(subjectLabel))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subjectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTop.setMinimumSize(new java.awt.Dimension(600, 56));
        panelTop.setPreferredSize(new java.awt.Dimension(600, 56));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emailTable;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelTop;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextArea textTextArea;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    private TableModel getEmailsTableModel()
    {
        String columnNames[] = {"From", "To", "Subject"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
        for(Claim c : claimListCurrent.getClaimList().values())
        {
            for(Email e : c.getEmailsList().getEmailList())
            {
                if(e.getTo().equals(garage.getName())){
                    emailList.add(e);
                    Vector<String> row = new Vector<String>();
                    row.add(e.getFrom());
                    row.add(e.getTo());
                    row.add(e.getSubject());
                    dtm.addRow(row);
                }
            }
        }
        emailTable.setModel(dtm);
        return dtm;
    }
    private class EmailsRowListener implements ListSelectionListener
    {
        @Override
        public void valueChanged(ListSelectionEvent e)
        {
            if(e.getValueIsAdjusting())
                return;

            int row = e.getFirstIndex();
            Email email = emailList.getEmailList().get(row);
            fromLabel.setText(email.getFrom());
            toLabel.setText(email.getTo());
            subjectLabel.setText(email.getSubject());
            textTextArea.setText(email.getText());
            textTextArea.setEditable(false);
        }
    }
}
