/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PasswordChange.java
 *
 * Created on Oct 23, 2011, 10:23:12 AM
 */

package xcompany.userInterface;

/**
 *
 * @author Emertat
 */
public class PasswordChange extends javax.swing.JPanel {

    /** Creates new form PasswordChange */
    public PasswordChange() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMandatoryChangePass = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldCurrentPassM = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldNewPassM = new javax.swing.JPasswordField();
        jButtonChangePassMandatory = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("Current Password");

        jPasswordFieldCurrentPassM.setText("jPasswordField1");

        jLabel3.setText("New Password");

        jPasswordFieldNewPassM.setText("jPasswordField1");

        jButtonChangePassMandatory.setText("Change Password");
        jButtonChangePassMandatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePassMandatoryActionPerformed(evt);
            }
        });

        jLabel7.setText("Password Change");

        javax.swing.GroupLayout jPanelMandatoryChangePassLayout = new javax.swing.GroupLayout(jPanelMandatoryChangePass);
        jPanelMandatoryChangePass.setLayout(jPanelMandatoryChangePassLayout);
        jPanelMandatoryChangePassLayout.setHorizontalGroup(
            jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMandatoryChangePassLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButtonChangePassMandatory)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanelMandatoryChangePassLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMandatoryChangePassLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(jPanelMandatoryChangePassLayout.createSequentialGroup()
                        .addGroup(jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldNewPassM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldCurrentPassM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))))
        );
        jPanelMandatoryChangePassLayout.setVerticalGroup(
            jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMandatoryChangePassLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addGroup(jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldCurrentPassM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelMandatoryChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldNewPassM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButtonChangePassMandatory)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMandatoryChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMandatoryChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangePassMandatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePassMandatoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangePassMandatoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangePassMandatory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelMandatoryChangePass;
    private javax.swing.JPasswordField jPasswordFieldCurrentPassM;
    private javax.swing.JPasswordField jPasswordFieldNewPassM;
    // End of variables declaration//GEN-END:variables

}
